### ISSUE TITLE
Improve messaging

### ISSUE THREAD

**Issue by S4WA** [S4WA/SoundCloud-Player#21]
bruh https://stackoverflow.com/questions/27383224/chrome-extension-long-lived-message-connection-how-to-use-callback-functions

**Comment by S4WA** [comment]
why am i so stoopid

**Comment by S4WA** [comment]
i notice that my extension is the highest memory footprint on my environment 
i guess i gotta improve more

**Comment by S4WA** [comment]
> i notice that my extension is the highest memory footprint on my environment i guess i gotta improve more

![image](https://user-images.githubusercontent.com/24929259/203392257-184d0f3b-a6d9-424e-89c4-a6ab23ceaeda.png)
:tf:

**Comment by apades** [comment]
a new way to listen audio event change with out interval 1s update to get page innerText, use this script in [Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo)
``` js
(function() {
    'use strict';
let _createElement = document.createElement.bind(document)

let index = 0
document.createElement = (...args) => {
  let el = _createElement(...args)
  if (args[0] === 'audio') {
    console.log('create audio', el)
    el.setAttribute('data-index', index++)
    el.addEventListener('play', (e) => {
      let el = e.target
      // let index = el.getAttribute('data-index')
      console.log('play', el)
    })
  }
  return el
}
})();
```
then you can see that website create a audio el, i click page play button and trigger this el play event, [all audio event in mdn](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio#events)
![Image](https://user-images.githubusercontent.com/36807043/205224965-40508409-5a3a-481a-9214-41a9c931a0b5.png)

**Comment by S4WA** [comment]
cool! i'll check it tonight. thanks apades!

**Comment by S4WA** [comment]
sometime my likes on sc (https://soundcloud.com/you/likes) won't load new items and kept loading forever unless i reload the page. wonder if my code is causing it or it's just sc side's fault.
![image](https://user-images.githubusercontent.com/24929259/205307697-024cd402-5666-4434-885f-3744452fcb72.png)

**Comment by S4WA** [comment]
and also this bug isn't reproducible.

**Comment by apades** [comment]
i think this is network problom&nbsp;&nbsp;or soundcould lazy load bug, maybe you can open devTools to check this error
&nbsp;


apad
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yuri ***@***.***&gt;; 
发送时间: 2022年12月2日(星期五) 晚上9:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [S4WA/SoundCloud-Player] Improve messaging (Issue #21)





 
sometime my likes on sc (https://soundcloud.com/you/likes) won't load new items and kept loading forever unless i reload the page. wonder if my code is causing it or it's just sc side's fault.

**Comment by S4WA** [comment]
sorry i accidentally deleted my comment.
i'll check devtool when it happened again.

**Comment by S4WA** [comment]
will seriously have to deal with it since i had a little change in my code around messaging and it became slower (i think it's not responding because of the nullpo kind of)

**Comment by S4WA** [comment]
1244f06
