### ISSUE TITLE
dark theme 

### ISSUE THREAD

**Issue by ghost** [S4WA/soundcloud-player#9]
u made a such a great thing 

but if u just give the option for dark theme 
and more options for setting coz some times i just want to hide the frame or artwork

**Comment by S4WA** [comment]
The dark theme is done. I'll work on the compact view mode sooner.

**Comment by S4WA** [comment]
oops

**Comment by S4WA** [comment]
Let's add a function that opens new sc tab when user clicks any buttons. 
Cuz there's no artwork nor title.

**Comment by S4WA** [comment]
it doesn't .attr('checked', properly) as well

**Comment by S4WA** [comment]
todo: add '.DS_store' to ignore file

**Comment by S4WA** [comment]
> it doesn't .attr('checked', '') properly as well

fixed.



> todo: add '.DS_store' to ignore file

added.

**Comment by S4WA** [comment]
リンク＋時間がコピーされない

コピーのボタンのIDをClassにする。

**Comment by S4WA** [comment]
> Let's add a function that opens new sc tab when user clicks any buttons. Cuz there's no artwork nor title.

not yet


> TODO: リンク＋時間がコピーされない
> 
> コピーのボタンのIDをClassにする。 #16

done

**Comment by S4WA** [comment]
> > Let's add a function that opens new sc tab when user clicks any buttons. Cuz there's no artwork nor title.
> 
> not yet
> 
> > TODO: リンク＋時間がコピーされない
> > コピーのボタンのIDをClassにする。 #16
> 
> done

ITS ALL DONE BABY
